#!/bin/bash

echo -n "What's your name? : "
read name

echo -n "When is your birthday? : "
read birthday

case $name in
  taka)
;;
  $birthday in
  19931004)
  echo "Welcome back Taka!"
;;
  *)
  echo "You're not my master!"
;;
esac
