#!/bin/bash

echo -n "What's your name? : "
read name

echo -n "When is your birthday? : "
read birthday

if [ $name = 'taka' ] && [ $birthday = '19931004' ] ; then
  echo "Welcome back Taka!"
else
  echo "You're not my master!"
fi
